### ISSUE TITLE
Could not send request with credentials = true

### ISSUE THREAD

**Issue by iamkacperwasik** [bridgedxyz/services#20]
**Describe the bug**
Could not send request with credentials = true

**To Reproduce**
```js
axios.get('....', {
withCredentials: true
})
```

**Expected behavior**
Credentials would be transferred along with request

**Screenshots**
`Access to XMLHttpRequest at 'https://cors.bridged.cc/....' from origin '...' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.4]
 - Browser [e.g. brave)

**Comment by softmarshmallow** [comment]
Did you managed to make it work as your desired results on app.cors.bridged.cc?
or is it just happening on cors.bridged.cc

**Comment by iamkacperwasik** [comment]
I'm using `https://cors.bridged.cc`

```ts
const CORS = 'https://cors.bridged.cc';


const fetchVideoUrl = async (url: string): Promise<string> => {
   const response = await axios.get<string>(resolveUrl(`${CORS}/${url}`), {
      withCredentials: true
   });
};
```

**Comment by iamkacperwasik** [comment]
Is it going to be resolved in the near time? It blocks me from fetching pages that requires authentication.

**Comment by softmarshmallow** [comment]
> I'm using `https://cors.bridged.cc`
> 
> ```ts
> const CORS = 'https://cors.bridged.cc';
> 
> const fetchVideoUrl = async (url: string): Promise<string> => {
>    const response = await axios.get<string>(resolveUrl(`${CORS}/${url}`), {
>       withCredentials: true
>    });
> };
> ```

Is this the full code? is the actual auth header included in axios instance?

We'll fix it right away if we find a solution to it.

**Comment by iamkacperwasik** [comment]
> Is this the full code?

yes, `withCredentials: true` option automatically sets cookies on request header
in my case, cookies would be filled from browser (it's a chrome extension)

**Comment by iamkacperwasik** [comment]
I'm not an expert but I think that `Access-Control-Allow-Origin` should be of value `*`.
I don't know if it would be enough to get it to work.

**Comment by softmarshmallow** [comment]
Can you try the same request on https://app.cors.bridged.cc (which is a browser environment testing tool)

and share the error log, request/response results from the network panel from chrome developer tools

**Comment by iamkacperwasik** [comment]
![image](https://user-images.githubusercontent.com/57839948/108131501-a71ab600-70b1-11eb-9684-738c7bd2839d.png)

![image](https://user-images.githubusercontent.com/57839948/108131461-979b6d00-70b1-11eb-9257-eb9e32ffa4b3.png)

**Comment by iamkacperwasik** [comment]
![image](https://user-images.githubusercontent.com/57839948/108132478-31174e80-70b3-11eb-81c9-47d016e37779.png)

**Comment by softmarshmallow** [comment]
I think i should be trying that myself. if it's possible, can you share us the full request url?

**Comment by iamkacperwasik** [comment]
It's a random Facebook video

https://video.xx.fbcdn.net/v/t42.9040-2/126328829_313833672914661_1988925464807943958_n.mp4?_nc_cat=103&ccb=3&_nc_sid=985c63&efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ohc=cDTwQfFwNVQAX8nfVga&_nc_ht=video.fpoz3-1.fna&oh=35dd6ed2cb00080af4f64cfe47259f6c&oe=602C72F2

**Comment by softmarshmallow** [comment]
And please note that cors.bridged.cc uses https://github.com/Rob--W/cors-anywhere/
Check if this work on cors-anywhere.herokuapp.com

And also read this blog https://medium.com/bridgedxyz/cors-anywhere-for-everyone-free-reliable-cors-proxy-service-73507192714e

**Comment by softmarshmallow** [comment]
![image](https://user-images.githubusercontent.com/16307013/108132931-0e0e8e00-70f7-11eb-9761-b0b0a5835c6e.png)
It works fine for me. tested via insomnia. maybe you should be adding x-requested-with and origin header.
Are those present?

**Comment by iamkacperwasik** [comment]
I'll check it

**Comment by iamkacperwasik** [comment]
Now it works in postman without credentials, but with `withCredentials: true` it throws:

![image](https://user-images.githubusercontent.com/57839948/108133462-e39be100-70b4-11eb-991d-0db8caefede9.png)

**Comment by softmarshmallow** [comment]
> Now it works in postman without credentials, but with `withCredentials: true` it throws:
> 
> ![image](https://user-images.githubusercontent.com/57839948/108133462-e39be100-70b4-11eb-991d-0db8caefede9.png)

That's probably axios' designed behaviour
1. why do you need with credentials flag?
2. what happens without em' and just provide auth data in the global header?
3.

**Comment by iamkacperwasik** [comment]
> 1. why do you need with credentials flag?

some posts on Facebook requires me to be authenticated, so I need to pass the cookies to fetch content

**Comment by iamkacperwasik** [comment]
I think it is impossible to send cookies that way.

**Comment by softmarshmallow** [comment]
@GwonHeeJun  Any ideas? I'm out of guesses.

@iamkacperwasik  Maybe you should also inquery this on the facebook side too,

**Comment by iamkacperwasik** [comment]
I know whats wrong.

https://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i#answer-19744754
